### ISSUE TITLE
contentBytes如果刚好是blocksize倍数长度

### ISSUE THREAD

**Issue by ixqbar** [yanue/aes-cbc-pkcs7#1]
```
byte[] contentBytes = content.getBytes(StandardCharsets.UTF_8);
int pad = blockSize - (contentBytes.length % blockSize); //  这里contentBytes如果刚好是blocksize倍数长度 可以不用补吧
```

**Comment by yanue** [comment]
PKCS7是当下各大加密算法都遵循的数据填充算法，且 OpenSSL 加密算法簇的默认填充算法就是 PKCS7。
AES-128, AES-192, AES-256 的数据块长度分别为 128/8=16bytes, 192/8=24bytes, 256/8=32bytes。

其实PKCS7理解起来非常简单，使用需填充长度的数值 paddingSize 所表示的ASCII码 paddingChar = chr(paddingSize)对数据进行冗余填充。
注意，当待加密数据长度为 16 的整数倍时，填充的长度反而是最大的，要填充 16 字节，为什么呢？因为 "PKCS7" 拆包时会按协议取最后一个字节所表征的数值长度作为数据填充长度，如果因真实数据长度恰好为 16 的整数倍而不进行填充，则拆包时会导致真实数据丢失。

为什么是冗余填充呢？因为即便你的数据长度符合blockSize的整数倍时，也需要填充，填充的长度反而是最大的，要填充blockSize个char(blockSize)字符在数据尾部，这样牺牲了数据长度的做法是为了更为灵活透明的去解包数据，发送端和接收端不需要约定好blockSize，接收端总能通过数据包的最后一个字符得到填充的数据长度。

[https://segmentfault.com/a/1190000019793040](https://segmentfault.com/a/1190000019793040)

**Comment by ixqbar** [comment]
小白的意思是可以优化不用补了

**Comment by yanue** [comment]
我看了下其他语言也是相同填充算法,所以看到了上面的那条链接的解释
